export const PEK_URL = process.env.GATSBY_PEK_URL || ''
export const GITHUB_ORG_URL = process.env.GATSBY_GITHUB_ORG_URL || ''
export const YOUTUBE_CHANNEL_URL = process.env.GATSBY_YOUTUBE_CHANNEL_URL || ''
export const FACEBOOK_PAGE_URL = process.env.GATSBY_FACEBOOK_PAGE_URL || ''
export const RICKROLL_URL = process.env.GATSBY_RICKROLL_URL || ''
export const PUBLIC_EMAIL = process.env.GATSBY_PUBLIC_EMAIL || ''
export const CURRENT_COURSE_FORM_URL = process.env.GATSBY_CURRENT_COURSE_FORM_URL || ''
export const CURRENT_COURSE_SEMESTER = process.env.GATSBY_CURRENT_COURSE_SEMESTER || ''
